version: '3.8'

services:
  backend:
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - backend_node_modules:/app/node_modules

  frontend:
    ports:
      - "8080:80"

volumes:
  backend_node_modules: